export const CART_DUMMY_DATA = [
  {
    id: 1,
    productId: 101,
    nameAr: "باراسيتامول",
    nameEn: "Paracetamol Tablets",
    concentration: "500mg",
    price: 25,
    beforeDiscount: 30,
    qty: 2,
    total: 50,
    availableQty: 10,
    imageUrl:
      "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/agzakahan-public-portal/cetafen.png",
  },
  {
    id: 2,
    productId: 202,
    nameAr: "شامبو مضاد للقشرة",
    nameEn: "Anti-Dandruff Shampoo",
    concentration: "200ml",
    price: 75,
    beforeDiscount: 90,
    qty: 1,
    total: 75,
    availableQty: 5,
    imageUrl:
      "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/agzakahan-public-portal/spohxo.png",
  },
  {
    id: 3,
    productId: 303,
    nameAr: "كريم ترطيب البشرة",
    nameEn: "Moisturizing Skin Cream",
    concentration: "100ml",
    price: 120,
    beforeDiscount: 150,
    qty: 3,
    total: 360,
    availableQty: 6,
    imageUrl:
      "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/agzakahan-public-portal/vaporub.png",
  },
  {
    id: 4,
    productId: 404,
    nameAr: "فيتامين سي مكمل غذائي",
    nameEn: "Vitamin C Supplement",
    concentration: "1000mg",
    price: 90,
    beforeDiscount: 110,
    qty: 1,
    total: 90,
    availableQty: 8,
    imageUrl:
      "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/agzakahan-public-portal/benylyn.png",
  },
  {
    id: 5,
    productId: 505,
    nameAr: "سيروم للشعر التالف",
    nameEn: "Hair Repair Serum",
    concentration: "50ml",
    price: 150,
    beforeDiscount: 180,
    qty: 2,
    total: 300,
    availableQty: 4,
    imageUrl:
      "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/agzakahan-public-portal/librax.png",
  },
];
