export const KANBAN_MODIFIED_MOCK = {
  results: 24,
  status: "success",
  content: [
    {
      _id: "user-01",
      nameAr: "تقي الدين أحمد علي عمر",
      nameEn: "Takie Eldeen Ahmed Ali Omar",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/takie.eldeen1998-29803280104897",
      email: "takie@agzakhana.com",
      joiningDate: "2025-10-31T22:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-01", nameAr: "القاهرة", nameEn: "Cairo" },
      branch: {
        _id: "branch-01",
        nameAr: "فرع الخلفاوي",
        nameEn: "Elkhalafawy Branch",
      },
      roles: [
        {
          _id: "69033b5816436fe7cb655d17",
          nameAr: "مدير المخزون",
          nameEn: "Inventory Manager",
        },
        {
          _id: "69033bd016436fe7cb655d20",
          nameAr: "مسؤول المشتريات معدل",
          nameEn: "Procurement Officer",
        },
      ],
    },
    {
      _id: "user-02",
      branch: {
        _id: "branch-02",
        nameAr: "فرع المهندسين",
        nameEn: "Mohandessin Branch",
      },
      nameAr: "محمد خالد عبد السلام",
      nameEn: "Mohamed Khaled Abdelsalam",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/islam-29803280104899",
      email: "m.khaled@agzakhana.com",
      joiningDate: "2025-10-20T22:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-02", nameAr: "الجيزة", nameEn: "Giza" },
      roles: [
        { _id: "role-01", nameAr: "صيدلي", nameEn: "Pharmacist" },
        {
          _id: "role-02",
          nameAr: "مدير الورديات",
          nameEn: "Shift Supervisor",
        },
      ],
    },
    {
      _id: "user-03",
      nameAr: "أحمد محمود عبد الرحمن",
      nameEn: "Ahmed Mahmoud Abdelrahman",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/gHisham-2980104897",
      email: "ahmed.mahmoud@agzakhana.com",
      joiningDate: "2025-09-15T22:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-03", nameAr: "الإسكندرية", nameEn: "Alexandria" },
      branch: {
        _id: "branch-01",
        nameAr: "فرع الخلفاوي",
        nameEn: "Elkhalafawy Branch",
      },
      roles: [{ _id: "role-03", nameAr: "أمين مخزن", nameEn: "Storekeeper" }],
    },
    {
      _id: "user-04",
      nameAr: "مريم حسين مصطفى",
      nameEn: "Maryam Hussein Mostafa",
      imageUrl: null,
      email: "maryam.hussein@agzakhana.com",
      joiningDate: "2025-08-10T22:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-04", nameAr: "المنصورة", nameEn: "Mansoura" },
      branch: {
        _id: "branch-01",
        nameAr: "فرع الخلفاوي",
        nameEn: "Elkhalafawy Branch",
      },
      roles: [{ _id: "role-04", nameAr: "محاسب", nameEn: "Accountant" }],
    },
    {
      _id: "user-05",
      nameAr: "سيف الدين علاء محمد",
      nameEn: "Saif Eldin Alaa Mohamed",
      imageUrl: null,
      email: "saif.alaa@agzakhana.com",
      joiningDate: "2025-11-01T22:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-05", nameAr: "أسيوط", nameEn: "Assiut" },
      branch: {
        _id: "branch-02",
        nameAr: "فرع المهندسين",
        nameEn: "Mohandessin Branch",
      },
      roles: [{ _id: "role-05", nameAr: "كاشير", nameEn: "Cashier" }],
    },
    {
      _id: "user-06",
      nameAr: "نورهان طارق عبد الهادي",
      nameEn: "Norhan Tarek Abdelhady",
      imageUrl: null,
      email: "norhan.tarek@agzakhana.com",
      joiningDate: "2025-07-25T22:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-06", nameAr: "طنطا", nameEn: "Tanta" },
      branch: {
        _id: "branch-02",
        nameAr: "فرع المهندسين",
        nameEn: "Mohandessin Branch",
      },
      roles: [{ _id: "role-06", nameAr: "صيدلي", nameEn: "Pharmacist" }],
    },
    {
      _id: "user-07",
      nameAr: "خالد عبد العزيز سالم",
      nameEn: "Khaled Abdelaziz Salem",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/soska-29803280155897",
      email: "khaled.salem@agzakhana.com",
      joiningDate: "2025-06-12T22:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-07", nameAr: "سوهاج", nameEn: "Sohag" },
      branch: null,
      roles: [
        { _id: "role-07", nameAr: "مساعد صيدلي", nameEn: "Pharmacy Assistant" },
      ],
    },
    {
      _id: "user-08",
      nameAr: "شهد عبد الله محمد",
      nameEn: "Shahd Abdullah Mohamed",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/asalah-29403150104897",
      email: "shahd.abdullah@agzakhana.com",
      joiningDate: "2025-05-01T22:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-08", nameAr: "الزقازيق", nameEn: "Zagazig" },
      branch: {
        _id: "branch-04",
        nameAr: "فرع شبرا",
        nameEn: "Shubra Branch",
      },
      roles: [{ _id: "role-08", nameAr: "مدير فرع", nameEn: "Branch Manager" }],
    },
    {
      _id: "user-09",
      nameAr: "إسلام حسن عبد الفتاح",
      nameEn: "Islam Hassan Abdelfattah",
      imageUrl: null,
      email: "islam.hassan@agzakhana.com",
      joiningDate: "2025-10-02T22:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-09", nameAr: "الفيوم", nameEn: "Fayoum" },
      branch: {
        _id: "branch-04",
        nameAr: "فرع شبرا",
        nameEn: "Shubra Branch",
      },
      roles: [{ _id: "role-01", nameAr: "صيدلي", nameEn: "Pharmacist" }],
    },
    {
      _id: "user-10",
      nameAr: "إسراء محسن محمد",
      nameEn: "Esraa Mohsen Mohamed",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/ayat-29201150104874",
      email: "esraa.mohsen@agzakhana.com",
      joiningDate: "2025-04-20T22:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-10", nameAr: "دمياط", nameEn: "Damietta" },
      branch: {
        _id: "branch-05",
        nameAr: "فرع المعادي",
        nameEn: "Maadi Branch",
      },
      roles: [
        {
          _id: "role-09",
          nameAr: "مسؤول خدمة العملاء",
          nameEn: "Customer Service",
        },
      ],
    },
    {
      _id: "user-11",
      nameAr: "طارق عبد الحميد منصور",
      nameEn: "Tarek Abdelhamid Mansour",
      imageUrl: null,
      email: "tarek.mansour@agzakhana.com",
      joiningDate: "2025-11-02T22:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-11", nameAr: "بورسعيد", nameEn: "Port Said" },
      branch: {
        _id: "branch-05",
        nameAr: "فرع المعادي",
        nameEn: "Maadi Branch",
      },
      roles: [
        { _id: "role-10", nameAr: "مدير المخزون", nameEn: "Inventory Manager" },
      ],
    },
    {
      _id: "user-12",
      nameAr: "منة الله أحمد إبراهيم",
      nameEn: "Menna Allah Ahmed Ibrahim",
      imageUrl: null,
      email: "menna.ahmed@agzakhana.com",
      joiningDate: "2025-03-10T22:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-12", nameAr: "الإسماعيلية", nameEn: "Ismailia" },
      branch: {
        _id: "branch-06",
        nameAr: "فرع الهرم",
        nameEn: "Haram Branch",
      },
      roles: [{ _id: "role-11", nameAr: "كاشير", nameEn: "Cashier" }],
    },
    {
      _id: "user-13",
      nameAr: "مصطفى سيد عبد الباسط",
      nameEn: "Mostafa Sayed Abdelbaset",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/seif-28401160104897",
      email: "mostafa.sayed@agzakhana.com",
      joiningDate: "2025-09-12T22:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-13", nameAr: "قنا", nameEn: "Qena" },
      branch: {
        _id: "branch-06",
        nameAr: "فرع الهرم",
        nameEn: "Haram Branch",
      },
      roles: [
        { _id: "role-02", nameAr: "مدير الورديات", nameEn: "Shift Supervisor" },
      ],
    },
    {
      _id: "user-14",
      nameAr: "بسمة علي أحمد",
      nameEn: "Basma Ali Ahmed",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/ali-29803280554897",
      email: "basma.ali@agzakhana.com",
      joiningDate: "2025-02-18T22:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-14", nameAr: "بنها", nameEn: "Banha" },
      branch: {
        _id: "branch-03",
        nameAr: "فرع مدينة نصر",
        nameEn: "Nasr City Branch",
      },
      roles: [{ _id: "role-08", nameAr: "مدير فرع", nameEn: "Branch Manager" }],
    },
    {
      _id: "user-15",
      nameAr: "عمر خالد محمد",
      nameEn: "Omar Khaled Mohamed",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/bilalFarag-2980511280104855",
      email: "omar.khaled@agzakhana.com",
      joiningDate: "2025-01-22T22:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-15", nameAr: "دمهنهور", nameEn: "Damanhour" },
      branch: {
        _id: "branch-04",
        nameAr: "فرع شبرا",
        nameEn: "Shubra Branch",
      },
      roles: [{ _id: "role-03", nameAr: "أمين مخزن", nameEn: "Storekeeper" }],
    },
    {
      _id: "user-16",
      nameAr: "سارة أحمد محمد",
      nameEn: "Sara Ahmed Mohamed",
      imageUrl: null,
      email: "sara.ahmed@agzakhana.com",
      joiningDate: "2025-03-30T22:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-16", nameAr: "بني سويف", nameEn: "Beni Suef" },
      branch: {
        _id: "branch-05",
        nameAr: "فرع المعادي",
        nameEn: "Maadi Branch",
      },
      roles: [{ _id: "role-06", nameAr: "صيدلي", nameEn: "Pharmacist" }],
    },
    {
      _id: "user-17",
      nameAr: "محمد طارق حسن",
      nameEn: "Mohamed Tarek Hassan",
      imageUrl: null,
      email: "mohamed.tarek@agzakhana.com",
      joiningDate: "2025-04-11T22:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-17", nameAr: "العريش", nameEn: "Arish" },
      branch: {
        _id: "branch-01",
        nameAr: "فرع الخلفاوي",
        nameEn: "Elkhalafawy Branch",
      },
      roles: [
        {
          _id: "role-09",
          nameAr: "مسؤول خدمة العملاء",
          nameEn: "Customer Service",
        },
      ],
    },
    {
      _id: "user-18",
      nameAr: "إيمان نبيل إبراهيم",
      nameEn: "Eman Nabil Ibrahim",
      imageUrl: null,
      email: "eman.nabil@agzakhana.com",
      joiningDate: "2025-08-05T22:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-18", nameAr: "أسوان", nameEn: "Aswan" },
      branch: {
        _id: "branch-06",
        nameAr: "فرع الهرم",
        nameEn: "Haram Branch",
      },
      roles: [{ _id: "role-04", nameAr: "محاسب", nameEn: "Accountant" }],
    },
    {
      _id: "user-19",
      nameAr: "عبد الرحمن محمد يوسف",
      nameEn: "Abdelrahman Mohamed Youssef",
      imageUrl: null,
      email: "abdelrahman.youssef@agzakhana.com",
      joiningDate: "2025-02-12T22:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-19", nameAr: "السويس", nameEn: "Suez" },
      branch: {
        _id: "branch-04",
        nameAr: "فرع شبرا",
        nameEn: "Shubra Branch",
      },
      roles: [{ _id: "role-01", nameAr: "صيدلي", nameEn: "Pharmacist" }],
    },
    {
      _id: "user-20",
      nameAr: "ملك خالد إبراهيم",
      nameEn: "Malak Khaled Ibrahim",
      imageUrl: null,
      email: "malak.khaled@agzakhana.com",
      joiningDate: "2025-09-01T22:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-20", nameAr: "الفيوم", nameEn: "Fayoum" },
      branch: {
        _id: "branch-02",
        nameAr: "فرع المهندسين",
        nameEn: "Mohandessin Branch",
      },
      roles: [
        { _id: "role-07", nameAr: "مساعد صيدلي", nameEn: "Pharmacy Assistant" },
      ],
    },
    {
      _id: "user-21",
      nameAr: "آدم هشام محمود",
      nameEn: "Adam Hesham Mahmoud",
      imageUrl: null,
      email: "adam.hesham@agzakhana.com",
      joiningDate: "2025-10-12T22:00:00.000Z",
      gender: "MAALE",
      city: { _id: "city-21", nameAr: "مرسى مطروح", nameEn: "Mersa Matruh" },
      branch: {
        _id: "branch-05",
        nameAr: "فرع المعادي",
        nameEn: "Maadi Branch",
      },
      roles: [{ _id: "role-03", nameAr: "أمين مخزن", nameEn: "Storekeeper" }],
    },
    {
      _id: "user-22",
      nameAr: "جودي أحمد سمير",
      nameEn: "Judy Ahmed Samir",
      imageUrl: null,
      email: "judy.samir@agzakhana.com",
      joiningDate: "2025-05-22T22:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-22", nameAr: "دمياط", nameEn: "Damietta" },
      branch: {
        _id: "branch-03",
        nameAr: "فرع مدينة نصر",
        nameEn: "Nasr City Branch",
      },
      roles: [
        { _id: "role-10", nameAr: "مدير المخزون", nameEn: "Inventory Manager" },
      ],
    },
    {
      _id: "user-23",
      nameAr: "فهد محمد عبد الحميد",
      nameEn: "Fahd Mohamed Abdelhamid",
      imageUrl: null,
      email: "fahd.abdelhamid@agzakhana.com",
      joiningDate: "2025-01-10T22:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-23", nameAr: "الإسكندرية", nameEn: "Alexandria" },
      branch: {
        _id: "branch-06",
        nameAr: "فرع الهرم",
        nameEn: "Haram Branch",
      },
      roles: [
        { _id: "role-02", nameAr: "مدير الورديات", nameEn: "Shift Supervisor" },
      ],
    },
    {
      _id: "user-24",
      nameAr: "ريم علي صبري",
      nameEn: "Reem Ali Sabry",
      imageUrl: null,
      email: "reem.sabry@agzakhana.com",
      joiningDate: "2025-06-06T22:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-24", nameAr: "شبين الكوم", nameEn: "Shebin El Kom" },
      branch: {
        _id: "branch-02",
        nameAr: "فرع المهندسين",
        nameEn: "Mohandessin Branch",
      },
      roles: [
        {
          _id: "role-09",
          nameAr: "مسؤول خدمة العملاء",
          nameEn: "Customer Service",
        },
      ],
    },
  ],
} as const;
