import { StaffCountedActiveBranchesType } from "@/app/dashboard-types/staff-allocation";
import { APIListResponse } from "@/types/common";

export const ACTIVE_BRANCHES: APIListResponse<StaffCountedActiveBranchesType> =
  {
    status: "success",
    results: 18,
    content: [
      {
        _id: "branch-01",
        nameAr: "فرع الخلفاوي",
        nameEn: "Elkhalafawy Branch",
        count: 1,
      },
      {
        _id: "branch-02",
        nameAr: "فرع شبرا",
        nameEn: "Shoubra Branch",
        count: 1,
      },
      {
        _id: "branch-03",
        nameAr: "فرع المنيل",
        nameEn: "El Manyal Branch",
        count: 2,
      },
      {
        _id: "branch-04",
        nameAr: "فرع مدينة نصر",
        nameEn: "Nasr City Branch",
        count: 1,
      },
      {
        _id: "branch-05",
        nameAr: "فرع مصر الجديدة",
        nameEn: "Heliopolis Branch",
        count: 1,
      },
      {
        _id: "branch-06",
        nameAr: "فرع المعادي",
        nameEn: "Maadi Branch",
        count: 1,
      },
      {
        _id: "branch-07",
        nameAr: "فرع التجمع",
        nameEn: "New Cairo Branch",
        count: 1,
      },
      {
        _id: "branch-08",
        nameAr: "فرع الهرم",
        nameEn: "Haram Branch",
        count: 2,
      },
      {
        _id: "branch-09",
        nameAr: "فرع فيصل",
        nameEn: "Faisal Branch",
        count: 2,
      },
      {
        _id: "branch-10",
        nameAr: "فرع السادس من أكتوبر",
        nameEn: "6th of October Branch",
        count: 1,
      },
      {
        _id: "branch-11",
        nameAr: "فرع الشيخ زايد",
        nameEn: "Sheikh Zayed Branch",
        count: 2,
      },
      {
        _id: "branch-12",
        nameAr: "فرع حدائق الأهرام",
        nameEn: "Hadayek Al Ahram Branch",
        count: 2,
      },
      {
        _id: "branch-13",
        nameAr: "فرع روض الفرج",
        nameEn: "Rod El Farag Branch",
        count: 1,
      },
      {
        _id: "branch-14",
        nameAr: "فرع الزمالك",
        nameEn: "Zamalek Branch",
        count: 2,
      },
      {
        _id: "branch-15",
        nameAr: "فرع وسط البلد",
        nameEn: "Downtown Branch",
        count: 1,
      },
      {
        _id: "branch-16",
        nameAr: "فرع حلوان",
        nameEn: "Helwan Branch",
        count: 2,
      },
      {
        _id: "branch-17",
        nameAr: "فرع العباسية",
        nameEn: "Abbassia Branch",
        count: 1,
      },
      {
        _id: "branch-18",
        nameAr: "فرع بولاق",
        nameEn: "Boulak Branch",
        count: 2,
      },
    ],
  };

export const ALLOCATED_STAFF: APIListResponse<any> = {
  status: "success",
  results: 26,
  content: [
    {
      _id: "user-1",
      nameAr: "بسمة علي أحمد",
      nameEn: "Basma Ali Ahmed",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/ali-29803280554897",
      email: "basma.ali@agzakhana.com",
      joiningDate: "2025-02-18T22:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-14", nameAr: "بنها", nameEn: "Banha" },
      branch: { _id: "branch-18", nameAr: "بولاق", nameEn: "Boulak" },
      roles: [{ _id: "role-08", nameAr: "مدير فرع", nameEn: "Branch Manager" }],
    },
    {
      _id: "user-2",
      nameAr: "محمد عمر عبدالعاطي",
      nameEn: "Mohamed Omar Abdelaaty",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/moh-29803280554898",
      email: "mohamed.omar@agzakhana.com",
      joiningDate: "2024-11-05T09:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-01", nameAr: "القاهرة", nameEn: "Cairo" },
      branch: { _id: "branch-18", nameAr: "بولاق", nameEn: "Boulak" },
      roles: [{ _id: "role-03", nameAr: "موظف مبيعات", nameEn: "Sales Rep" }],
    },
    {
      _id: "user-3",
      nameAr: "نجلاء سمير حسن",
      nameEn: "Naglaa Samir Hassan",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/nag-29803280554899",
      email: "naglaa.samir@agzakhana.com",
      joiningDate: "2023-07-12T08:30:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-02", nameAr: "الإسكندرية", nameEn: "Alexandria" },
      branch: { _id: "branch-02", nameAr: "شبرا", nameEn: "Shoubra" },
      roles: [{ _id: "role-02", nameAr: "أمين مخزن", nameEn: "Storekeeper" }],
    },
    {
      _id: "user-4",
      nameAr: "أحمد سامي جاد",
      nameEn: "Ahmed Sami Gad",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/ahm-29803280554900",
      email: "ahmed.sami@agzakhana.com",
      joiningDate: "2024-02-20T10:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-03", nameAr: "المنصورة", nameEn: "Mansoura" },
      branch: { _id: "branch-03", nameAr: "المنيل", nameEn: "El Manyal" },
      roles: [
        { _id: "role-04", nameAr: "مشرف مبيعات", nameEn: "Sales Supervisor" },
      ],
    },
    {
      _id: "user-5",
      nameAr: "سارة محمود علي",
      nameEn: "Sara Mahmoud Ali",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/sar-29803280554901",
      email: "sara.mahmoud@agzakhana.com",
      joiningDate: "2022-12-01T13:15:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-04", nameAr: "طنطا", nameEn: "Tanta" },
      branch: { _id: "branch-04", nameAr: "مدينة نصر", nameEn: "Nasr City" },
      roles: [{ _id: "role-05", nameAr: "محاسب", nameEn: "Accountant" }],
    },
    {
      _id: "user-6",
      nameAr: "مصطفى نبيل حسين",
      nameEn: "Mostafa Nabil Hussein",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/most-29803280554902",
      email: "mostafa.nabil@agzakhana.com",
      joiningDate: "2025-03-01T07:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-05", nameAr: "المنيا", nameEn: "Minya" },
      branch: { _id: "branch-05", nameAr: "مصر الجديدة", nameEn: "Heliopolis" },
      roles: [
        { _id: "role-06", nameAr: "خدمة عملاء", nameEn: "Customer Service" },
      ],
    },
    {
      _id: "user-7",
      nameAr: "هند طارق أحمد",
      nameEn: "Hend Tarek Ahmed",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/hend-29803280554903",
      email: "hend.tarek@agzakhana.com",
      joiningDate: "2021-05-22T11:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-06", nameAr: "أسيوط", nameEn: "Assiut" },
      branch: { _id: "branch-06", nameAr: "المعادي", nameEn: "Maadi" },
      roles: [
        { _id: "role-07", nameAr: "مشرف مخزن", nameEn: "Warehouse Supervisor" },
      ],
    },
    {
      _id: "user-8",
      nameAr: "رامي إبراهيم محمد",
      nameEn: "Ramy Ibrahim Mohamed",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/ramy-29803280554904",
      email: "ramy.ibrahim@agzakhana.com",
      joiningDate: "2020-09-15T09:45:00.000Z",
      gender: "MALE",
      city: { _id: "city-07", nameAr: "بورسعيد", nameEn: "Port Said" },
      branch: { _id: "branch-07", nameAr: "التجمع", nameEn: "New Cairo" },
      roles: [{ _id: "role-03", nameAr: "موظف مبيعات", nameEn: "Sales Rep" }],
    },
    {
      _id: "user-9",
      nameAr: "منى خالد سليمان",
      nameEn: "Mona Khaled Suleiman",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/mona-29803280554905",
      email: "mona.khaled@agzakhana.com",
      joiningDate: "2023-03-10T14:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-08", nameAr: "المنوفية", nameEn: "Menoufia" },
      branch: { _id: "branch-08", nameAr: "الهرم", nameEn: "Haram" },
      roles: [{ _id: "role-02", nameAr: "أمين مخزن", nameEn: "Storekeeper" }],
    },
    {
      _id: "user-10",
      nameAr: "يوسف نادر ربيع",
      nameEn: "Youssef Nader Rabie",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/yous-29803280554906",
      email: "youssef.nader@agzakhana.com",
      joiningDate: "2024-06-30T12:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-09", nameAr: "الزقازيق", nameEn: "Zagazig" },
      branch: { _id: "branch-09", nameAr: "فيصل", nameEn: "Faisal" },
      roles: [
        { _id: "role-04", nameAr: "مشرف مبيعات", nameEn: "Sales Supervisor" },
      ],
    },
    {
      _id: "user-11",
      nameAr: "عائشة كريم سمير",
      nameEn: "Aisha Karim Samir",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/aish-29803280554907",
      email: "aisha.karim@agzakhana.com",
      joiningDate: "2022-01-18T08:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-10", nameAr: "قنا", nameEn: "Qena" },
      branch: {
        _id: "branch-10",
        nameAr: "السادس من أكتوبر",
        nameEn: "6th of October",
      },
      roles: [{ _id: "role-05", nameAr: "محاسب", nameEn: "Accountant" }],
    },
    {
      _id: "user-12",
      nameAr: "كريم بشير عيسى",
      nameEn: "Karim Basheer Eissa",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/karim-29803280554908",
      email: "karim.basheer@agzakhana.com",
      joiningDate: "2021-10-04T15:30:00.000Z",
      gender: "MALE",
      city: { _id: "city-11", nameAr: "الفيوم", nameEn: "Fayoum" },
      branch: {
        _id: "branch-11",
        nameAr: "الشيخ زايد",
        nameEn: "Sheikh Zayed",
      },
      roles: [
        { _id: "role-01", nameAr: "مدير عام", nameEn: "General Manager" },
      ],
    },
    {
      _id: "user-13",
      nameAr: "رانيا توفيق محمد",
      nameEn: "Rania Tawfiq Mohamed",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/rania-29803280554909",
      email: "rania.tawfiq@agzakhana.com",
      joiningDate: "2020-04-20T09:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-12", nameAr: "السويس", nameEn: "Suez" },
      branch: {
        _id: "branch-12",
        nameAr: "حدائق الأهرام",
        nameEn: "Hadayek Al Ahram",
      },
      roles: [
        { _id: "role-06", nameAr: "خدمة عملاء", nameEn: "Customer Service" },
      ],
    },
    {
      _id: "user-14",
      nameAr: "زياد فؤاد مرسي",
      nameEn: "Ziad Fouad Morsi",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/ziad-29803280554910",
      email: "ziad.fouad@agzakhana.com",
      joiningDate: "2019-08-11T10:30:00.000Z",
      gender: "MALE",
      city: { _id: "city-13", nameAr: "المنوف", nameEn: "Menouf" },
      branch: { _id: "branch-13", nameAr: "روض الفرج", nameEn: "Rod El Farag" },
      roles: [{ _id: "role-03", nameAr: "موظف مبيعات", nameEn: "Sales Rep" }],
    },
    {
      _id: "user-15",
      nameAr: "ليلى سمير توفيق",
      nameEn: "Laila Samir Tawfiq",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/laila-29803280554911",
      email: "laila.samir@agzakhana.com",
      joiningDate: "2024-04-01T09:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-15", nameAr: "الزمالك", nameEn: "Zamalek" },
      branch: { _id: "branch-14", nameAr: "الزمالك", nameEn: "Zamalek" },
      roles: [
        { _id: "role-04", nameAr: "مشرف مبيعات", nameEn: "Sales Supervisor" },
      ],
    },
    {
      _id: "user-16",
      nameAr: "محمود صبري رجب",
      nameEn: "Mahmoud Sabry Ragab",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/mahmoud-29803280554912",
      email: "mahmoud.sabry@agzakhana.com",
      joiningDate: "2023-11-20T08:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-16", nameAr: "وسط البلد", nameEn: "Downtown" },
      branch: { _id: "branch-15", nameAr: "وسط البلد", nameEn: "Downtown" },
      roles: [{ _id: "role-02", nameAr: "أمين مخزن", nameEn: "Storekeeper" }],
    },
    {
      _id: "user-17",
      nameAr: "أمل عادل حسين",
      nameEn: "Amal Adel Hussein",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/amal-29803280554913",
      email: "amal.adel@agzakhana.com",
      joiningDate: "2022-06-14T12:15:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-17", nameAr: "حلوان", nameEn: "Helwan" },
      branch: { _id: "branch-16", nameAr: "حلوان", nameEn: "Helwan" },
      roles: [
        { _id: "role-07", nameAr: "مشرف مخزن", nameEn: "Warehouse Supervisor" },
      ],
    },
    {
      _id: "user-18",
      nameAr: "طارق جابر احمد",
      nameEn: "Tarek Gaber Ahmed",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/tarek-29803280554914",
      email: "tarek.gaber@agzakhana.com",
      joiningDate: "2020-01-03T09:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-18", nameAr: "العباسية", nameEn: "Abbassia" },
      branch: { _id: "branch-17", nameAr: "العباسية", nameEn: "Abbassia" },
      roles: [{ _id: "role-03", nameAr: "موظف مبيعات", nameEn: "Sales Rep" }],
    },
    {
      _id: "user-19",
      nameAr: "إيمان رشاد علي",
      nameEn: "Iman Rashad Ali",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/iman-29803280554915",
      email: "iman.rashad@agzakhana.com",
      joiningDate: "2021-03-27T10:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-19", nameAr: "بولاق", nameEn: "Boulak" },
      branch: { _id: "branch-18", nameAr: "بولاق", nameEn: "Boulak" },
      roles: [
        { _id: "role-06", nameAr: "خدمة عملاء", nameEn: "Customer Service" },
      ],
    },
    {
      _id: "user-20",
      nameAr: "سعد سامح نصر",
      nameEn: "Saad Sameh Nasr",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/saad-29803280554916",
      email: "saad.sameh@agzakhana.com",
      joiningDate: "2018-09-09T09:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-20", nameAr: "المنيل", nameEn: "El Manyal" },
      branch: { _id: "branch-03", nameAr: "المنيل", nameEn: "El Manyal" },
      roles: [{ _id: "role-05", nameAr: "محاسب", nameEn: "Accountant" }],
    },
    {
      _id: "user-21",
      nameAr: "ماهر وائل جلال",
      nameEn: "Maher Wael Galal",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/maher-29803280554917",
      email: "maher.wael@agzakhana.com",
      joiningDate: "2019-02-14T07:30:00.000Z",
      gender: "MALE",
      city: { _id: "city-21", nameAr: "الشيخ زايد", nameEn: "Sheikh Zayed" },
      branch: {
        _id: "branch-11",
        nameAr: "الشيخ زايد",
        nameEn: "Sheikh Zayed",
      },
      roles: [{ _id: "role-08", nameAr: "مدير فرع", nameEn: "Branch Manager" }],
    },
    {
      _id: "user-22",
      nameAr: "هدى مروان أمين",
      nameEn: "Hoda Marwan Amin",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/hoda-29803280554918",
      email: "hoda.marwan@agzakhana.com",
      joiningDate: "2022-11-11T11:11:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-22", nameAr: "الزمالك", nameEn: "Zamalek" },
      branch: { _id: "branch-14", nameAr: "الزمالك", nameEn: "Zamalek" },
      roles: [
        { _id: "role-06", nameAr: "خدمة عملاء", nameEn: "Customer Service" },
      ],
    },
    {
      _id: "user-23",
      nameAr: "بدرية كامل يوسف",
      nameEn: "Badriya Kamel Youssef",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/badriya-29803280554919",
      email: "badriya.kamel@agzakhana.com",
      joiningDate: "2020-12-01T09:30:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-23", nameAr: "حلوان", nameEn: "Helwan" },
      branch: { _id: "branch-16", nameAr: "حلوان", nameEn: "Helwan" },
      roles: [{ _id: "role-02", nameAr: "أمين مخزن", nameEn: "Storekeeper" }],
    },
    {
      _id: "user-24",
      nameAr: "حسام كمال رجب",
      nameEn: "Hossam Kamal Ragab",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/hossam-29803280554920",
      email: "hossam.kamal@agzakhana.com",
      joiningDate: "2024-08-08T08:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-24", nameAr: "الهرم", nameEn: "Haram" },
      branch: { _id: "branch-08", nameAr: "الهرم", nameEn: "Haram" },
      roles: [
        { _id: "role-04", nameAr: "مشرف مبيعات", nameEn: "Sales Supervisor" },
      ],
    },
    {
      _id: "user-25",
      nameAr: "داليا طاهر سمير",
      nameEn: "Dalia Taher Samir",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/dalia-29803280554921",
      email: "dalia.taher@agzakhana.com",
      joiningDate: "2021-01-05T10:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-25", nameAr: "فيصل", nameEn: "Faisal" },
      branch: { _id: "branch-09", nameAr: "فيصل", nameEn: "Faisal" },
      roles: [{ _id: "role-03", nameAr: "موظف مبيعات", nameEn: "Sales Rep" }],
    },
    {
      _id: "user-26",
      nameAr: "زيان مراد سعيد",
      nameEn: "Zayan Murad Said",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/zayan-29803280554922",
      email: "zayan.murad@agzakhana.com",
      joiningDate: "2023-05-19T09:00:00.000Z",
      gender: "MALE",
      city: {
        _id: "city-26",
        nameAr: "حدائق الأهرام",
        nameEn: "Hadayek Al Ahram",
      },
      branch: {
        _id: "branch-12",
        nameAr: "حدائق الأهرام",
        nameEn: "Hadayek Al Ahram",
      },
      roles: [
        { _id: "role-06", nameAr: "خدمة عملاء", nameEn: "Customer Service" },
      ],
    },
    {
      _id: "user-27",
      nameAr: "محمد سامي حسن",
      nameEn: "Mohamed Sami Hassan",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/mohamed-39820394859",
      email: "mohamed.sami@agzakhana.com",
      joiningDate: "2024-11-10T22:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-05", nameAr: "الجيزة", nameEn: "Giza" },
      branch: {
        _id: "UNALLOCATED",
        nameAr: "موظفين غير معينيين",
        nameEn: "Unallocated Staff",
      },
      roles: [{ _id: "role-03", nameAr: "صيدلي", nameEn: "Pharmacist" }],
    },
    {
      _id: "user-28",
      nameAr: "سارة ياسر محمد",
      nameEn: "Sara Yasser Mohamed",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/sara-8932849234",
      email: "sara.yasser@agzakhana.com",
      joiningDate: "2025-01-04T22:00:00.000Z",
      gender: "FEMALE",
      city: { _id: "city-08", nameAr: "طنطا", nameEn: "Tanta" },
      branch: {
        _id: "UNALLOCATED",
        nameAr: "موظفين غير معينيين",
        nameEn: "Unallocated Staff",
      },
      roles: [
        { _id: "role-02", nameAr: "مساعد صيدلي", nameEn: "Pharmacy Assistant" },
      ],
    },
    {
      _id: "user-29",
      nameAr: "عمرو خالد فؤاد",
      nameEn: "Amr Khaled Fouad",
      imageUrl:
        "https://ukbahlwracfvnetnxlba.supabase.co/storage/v1/object/public/Dashboard-profile-pics/amr-12839123123",
      email: "amr.khaled@agzakhana.com",
      joiningDate: "2023-09-22T22:00:00.000Z",
      gender: "MALE",
      city: { _id: "city-02", nameAr: "الإسكندرية", nameEn: "Alexandria" },
      branch: {
        _id: "UNALLOCATED",
        nameAr: "موظفين غير معينيين",
        nameEn: "Unallocated Staff",
      },
      roles: [{ _id: "role-06", nameAr: "مسؤول مخزن", nameEn: "Store Keeper" }],
    },
  ],
};
