import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { AuthProvider } from "@/providers/auth-provider";
import TanstackProvider from "@/providers/tanstack-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html
      lang={locale}
      className={locale === "ar" ? "font-cairo" : "font-quicksand"}
      dir={locale === "ar" ? "rtl" : "ltr"}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100! min-h-screen max-w-[2180px] m-auto text-text-primary!`}
      >
        <AuthProvider>
          <NextIntlClientProvider>
            <TanstackProvider>
              <Header />
              <Navbar />
              <main className="">{children}</main>
              <Footer />
            </TanstackProvider>
          </NextIntlClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
