import mongoose from "mongoose";
export type UserType = {
  _id: mongoose.Types.ObjectId;
  id: mongoose.Types.ObjectId;
  name: string;
  email: string;
  imageUrl: string;
  role: string;
  createdAt: Date;
  updatedAt: Date;
  phoneNumber: string;
  password: string;
  passwordConfirmation: string;
  provider: "GOOGLE" | "LOCAL";
  isActive: boolean;
  address: string;
  gender: "MALE" | "FEMALE";
  birthDate: Date;
  activationToken: string;
};
